name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build image
      run: |
        IMAGE_NAME=ghcr.io/${{ github.repository }}
        docker build -t $IMAGE_NAME:${{ github.sha }} -t $IMAGE_NAME:latest .

    - name: Login to GHCR.io
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push the image to GHCR.io
      run: |
        IMAGE_NAME=ghcr.io/${{ github.repository }}
        docker push ghcr.io/${{ github.repository }}:${{ github.sha }}
        docker push ghcr.io/${{ github.repository }}:latest
